### ISSUE TITLE
编译安装成功后，运行仍然报错  ImportError: DLL load failed while importing rtmp_streaming: 找不到指定的模块。

### ISSUE THREAD

**Issue by qwert1887** [lipku/python_rtmpstream#29]
@lipku 您好，我在win10上直接通过`pip install rtmp_streming` 安装，运行报错"ImportError: DLL load failed while importing rtmp_streaming: 找不到指定的模块。"。 然后自己编译了ffmpeg，利用最新的代码安装`pip install .`，成功后运行依然报同样的错误。如果您遇到过类似的情况，希望您在百忙之中可以指点一二。感谢！
<img width="713" alt="1716357247399" src="https://github.com/lipku/python_rtmpstream/assets/48791623/a4deee88-5a27-4126-856c-6c51ca51beaf">

**Comment by qwert1887** [comment]
分别更换了Python3.10、Python3.8，以及x64的win10、win11，不太行，报错信息根本找不到地方入手，可以告知下可能要用的dll文件都有哪些吗？？？ @lipku

**Comment by qwert1887** [comment]
经过不断摸索，目前在windows10和windows11上，拷贝编译好的dll动态库后，利用pip install rtmp_streaming==0.0.5直接安装即可。如图，
![e88946edd476451cd690e5de3961e47](https://github.com/lipku/python_rtmpstream/assets/48791623/9b2325dd-95d6-4f6f-a551-104293cd85e9)

**Comment by ajiansoft** [comment]
@qwert1887 请问大佬拷贝哪里的dll到哪里？

**Comment by qwert1887** [comment]
> @qwert1887 请问大佬拷贝哪里的dll到哪里？

抱一丝,刚看到消息,我编译完ffmpeg后,从里面找的dll文件,你找找,找到后,15个dll文件全部放你环境中的  Library\bin\
