### ISSUE TITLE
安装之后报 [libopenh264 @ 0x2de4d80] Incorrect library version loaded Could not open video encoder!

### ISSUE THREAD

**Issue by Jacoo-ai** [lipku/python_rtmpstream#35]
您好，我在安装之后，运行 test_wav_stream.py时，有以下错误：
 [libopenh264 @ 0x2de4d80] Incorrect library version loaded Could not open video encoder!
请问这是因为什么呢？期待您的回复。

**Comment by likelyzhao** [comment]
同问

**Comment by likelyzhao** [comment]
> 您好，我在安装之后，运行 test_wav_stream.py时，有以下错误： [libopenh264 @ 0x2de4d80] Incorrect library version loaded Could not open video encoder! 请问这是因为什么呢？期待您的回复。

$ conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
$ conda install ffmpeg  
用conda 重装一下ffmpeg 可以解决

**Comment by Jacoo-ai** [comment]
> > 您好，我在安装之后，运行 test_wav_stream.py时，有以下错误： [libopenh264 @ 0x2de4d80] Incorrect library version loaded Could not open video encoder! 请问这是因为什么呢？期待您的回复。
> 
> $ conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge $ conda install ffmpeg 用conda 重装一下ffmpeg 可以解决

好的，谢谢！
